df_shoot <- read.csv("C:/Users/bluec/Desktop/NYPD_ZIP.csv", na.strings=c("","NA"))
df_shoot$OCCUR_DATE <- as.character(df_shoot$OCCUR_DATE)
df_shoot$OCCUR_TIME <- as.character(df_shoot$OCCUR_TIME)
df_shoot$OCCUR <- paste(df_shoot$OCCUR_DATE, df_shoot$OCCUR_TIME, sep=" ")
df_shoot$OCCUR <- as.POSIXct(df_shoot$OCCUR, format = "%m/%d/%Y %H:%M:%S")
df_shoot$year = lubridate::year(df_shoot$OCCUR)
df_shoot <- df_shoot%>%filter(!is.na(year) & !is.na(BORO))
df_shoot$hour = lubridate::hour(df_shoot$OCCUR)
df_shoot <- df_shoot %>% filter(!is.na(hour) & !is.na(BORO))
df_shoot = subset(df_shoot, PERP_AGE_GROUP != '940' & PERP_AGE_GROUP != '1020' & VIC_AGE_GROUP != 'UNKNOWN' & VIC_SEX != 'U')
df_shoot <- df_shoot %>% droplevels(df_shoot$VIC_AGE_GROUP)
df_shoot <- subset(df_shoot, PERP_AGE_GROUP != '940' & PERP_AGE_GROUP != '1020' & PERP_AGE_GROUP != 'UNKNOWN' & PERP_SEX != 'U')
df_shoot <- df_shoot %>% droplevels(df_shoot$PERP_AGE_GROUP)

write.csv(df_shoot,"C:/Users/bluec/Desktop/NYPD_SHOOTING_ZIP.csv", row.names = FALSE)
